# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ff163bb89e8d2a57617b19efa2685886"
name = "Migration 11"
handle = "migration-27"
application_url = "https://rising-chen-parliamentary-pursuit.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "docker-deployment.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://rising-chen-parliamentary-pursuit.trycloudflare.com/auth/callback",
  "https://rising-chen-parliamentary-pursuit.trycloudflare.com/auth/shopify/callback",
  "https://rising-chen-parliamentary-pursuit.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
